codecov:
  branch: master
  bot: aem
  notify:
    require_ci_to_pass: yes
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        branches: null

    patch:
      default:
        target: auto
        branches: null

    changes:
      default:
        branches: null

  ignore:
    - test/.*
    - .github/*

comment:
  layout: "header, diff, changes, uncovered"
  branches: "*"
  behavior: default
  paths:
    - src/.*
